pipeline{
  agent{
    docker{
      image 'python:2.7.16-slim'
    }
  

stages{
  stage('build'){
    when{
     changeset "**/vote/**"
    }
    steps{
      echo 'building vote app'
      dir('vote'){
        sh 'pip install -r requirements.txt'
      }
    }
  }

stage('test'){
  when{
   changeset "**/vote/**"
  }
  steps{
    echo 'running unit tests on vote app'
      dir('vote'){
        sh 'nosetests -v'
      }
    }
  }
}

post{
  always{
    echo 'the job is complete'
    }
  } 
}

