pipeline {
    agent any
    tools{
      maven 'Maven 3.6.1'
    }
    
    stages {
        stage('build') {
            steps {
                echo 'compiling worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        
        stage('test job') {
            steps {
                echo 'Running uniit tests on worker app'
            }
        }
        
        stage('package') {
            steps {
                echo 'packaging worker app'
            }
        }
    }
    
    post{
        always{
            echo 'Build pipeline is completed for worker app..'
        }
    }
}

